### ISSUE TITLE
Group member details not loading in chat view 

### ISSUE THREAD

**Issue by jevonmao** [Highschool-iOS-Devs/StudyHub#26]
When you tap on the upper right corner, the half modal come up and members are not loading.

**Comment by AndreasInk** [comment]
@AndreasInk

**Comment by AndreasInk** [comment]
It's only not loading due to the storage bucket not being set up properly for the dev branch and its partially not visible due to a UI bug

**Comment by AndreasInk** [comment]
Not sure how to fix the storage issue ^ any ideas @jevonmao

**Comment by AndreasInk** [comment]
Partially fixed (fixed UI part not issue with storage bucket)

**Comment by jevonmao** [comment]
Seems fixed
