### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by AndreasInk** [Highschool-iOS-Devs/StudyHub#7]
- [ ] If user doesn't select a topic, the app crashes on RecentsView2(), Firebase query error

- [ ] If toggle to other views a few times paired names go from the other person's name (correct) to your name and the other person's name (incorrect)

**Comment by jevonmao** [comment]
The first bug of crashing on RecentView will be fixed once I push with the new recent view UI. Because I am basically rewriting all the query code, and I will make sure it won't crash.

**Comment by jevonmao** [comment]
@AndreasInk How did you trigger the first bug? I thought once you registered, the onboarding will let you select topics.

**Comment by AndreasInk** [comment]
@jevonmao I think I changed the view in the code so that might be the issue or but we need to make sure the user is unable to bypass the Intro Customization view, I can do fix tho.

**Comment by jevonmao** [comment]
Okay, you look into bypassing on boarding. Just keep in mind that I am changing all the if else in ContentView into Switch statements to fix compiler error.

**Comment by AndreasInk** [comment]
Sounds good, I'm making one more quick edit and I pushed in the last few minutes so you may need to update before making any changes, and thank you!
